      - name: Validar mensajes de commit
        env:
          BASE: ${{ github.event.pull_request.base.sha }}
          HEAD: ${{ github.event.pull_request.head.sha }}
        run: |
          REGEX='^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-z0-9._-]+\))?!?: .+'
          FALLO=0

          MERGE_BASE=$(git merge-base "$BASE" "$HEAD")

          while IFS= read -r msg; do
            if ! [[ "$msg" =~ $REGEX ]]; then
              echo "::error::Commit no válido: '$msg'"
              FALLO=1
            fi
          done < <(git log --no-merges --format=%s "$MERGE_BASE..$HEAD")

          exit $FALLO